import { useState, useEffect } from "react";
import Head from "next/head";
import Comments from "../components/Comments";
import NewCommentForm from "../components/NewCommentForm";

import { Data } from "../Data";

export default function Home() {
    const { currentUser } = Data;
    const [comments, setComments] = useState([]);

    useEffect(() => {
        setComments(Data.comments);
    }, []);

    const newCommentHandler = (newComment) => {
        setComments([...comments, newComment]);
    };

    const deleteCommentHandler = (id) => {
        const commentsArray = [...comments];
        const deletedCommentArray = commentsArray.filter(
            (eachComment) => eachComment.id !== id
        );
        setComments(deletedCommentArray);
    };

    return (
        <div className="bg-indigo-50 min-h-screen">
            <Head>
                <title>Comment section</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="w-11/12 mx-auto max-w-3xl py-10 space-y-4">
                {comments.map((comment) => (
                    <Comments
                        key={comment.id}
                        com={comment}
                        currentUser={currentUser}
                        onDelete={deleteCommentHandler}
                    />
                ))}

                <div className="mt-4 bg-white p-4 md:p-6 lg:p-8 rounded-xl shadow-sm">
                    <NewCommentForm
                        currentUser={currentUser}
                        onSubmit={newCommentHandler}
                    />
                </div>
            </div>
        </div>
    );
}
