import Head from "next/head";
import Image from "next/image";
import Comments from "../components/Comments";

import { Data } from "../Data";

export default function Home() {
    const { currentUser, comments } = Data;
    console.log(comments);

    return (
        <div className="bg-blue-50 min-h-screen">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="w-11/12 mx-auto max-w-3xl pt-10 space-y-4">
                {comments.map((com) => (
                    <Comments key={com.id} />
                ))}
            </div>
        </div>
    );
}
